### ISSUE TITLE
RawFile LocalPV provisioner does not actually delete PV folders

### ISSUE THREAD

**Issue by jshin47** [openebs/rawfile-localpv#5]
Steps to reproduce

1. Delete a rawfile LocalPV `kubectl delete pvc myrawfile-pvc` or `kubectl delete pv pv-122133123`

2. The PV folder will not be deleted on the host file system. It will only be marked deleted with timestamp in the metadata JSON file.

`$ cat disk.meta
{"schema_version": 2, "volume_id": "pvc-4b772e0e-9c16-4a1c-961d-9a9ba236de2f", "created_at": 1605768126.6610372, "img_file": "/data/pvc-4b772e0e-9c16-4a1c-961d-9a9ba236de2f/disk.img", "size": 10737418240, "fs_type": "ext4", "deleted_at": 1605769609.8736064}`

**Comment by SeMeKh** [comment]
Sorry for the late update.
This is a known behavior, and a culprit of rawfile being in an alpha-ish state. I was too afraid to **delete** anything back when I was developing this. Now that this has been running in different environments for months, I feel more confident doing it for real. Will update soon.

**Comment by laurivosandi** [comment]
Please also update helm charts

**Comment by laurivosandi** [comment]
Bumping this issue  as well, as I understand something needs to invoke the `gc` entrypoint in `rawfile.py` but there is none.
